Repository ethnt/tilde, pull requests merged in 2022-05, with the labels that each got.

#18 Add custom Navi module, implement in profile
  flake.nix
  modules/home/programs/navi/default.nix
  profiles/home/navi/default.nix
Labels: feature

#22 `st-eturkeltaub1` tweaks
  .gitignore
  flake.nix
  hosts/eMac/default.nix
  hosts/st-eturkeltaub1/default.nix
  profiles/home/fish/default.nix
  profiles/home/gnupg/default.nix
  profiles/home/tmux/default.nix
  profiles/system/networking/default.nix
  users/ethan/home.nix
  users/eturkeltaub/home.nix
  users/eturkeltaub/secrets.nix
Labels: improvement

#24 Add more work shortcuts
  users/eturkeltaub/secrets.nix
Labels: improvement

#27 Alias `darwin-rebuild switch --flake .#` to `tilde`
  shell/tilde.toml
Labels: feature

#30 Add `tmuxp` module
  modules/home/programs/tmuxp/default.nix
  profiles/home/tmux/default.nix
  users/eturkeltaub/home.nix
  users/eturkeltaub/secrets.nix
Labels: feature

#31 Add file nesting to VSCode
  profiles/home/vscode/default.nix
  users/eturkeltaub/secrets.nix
Labels: improvement

#32 Fix Navi shortcut
  users/eturkeltaub/secrets.nix
Labels: bug

#33 Update `tmuxp` workspaces
  users/ethan/home.nix
  users/eturkeltaub/home.nix
  users/eturkeltaub/secrets.nix
Labels: improvement

#34 Fix `$PATH` and `$NIX_PATH`
  flake.lock
  flake.nix
  hosts/eMac/default.nix
  hosts/st-eturkeltaub1/default.nix
  lib/compat/darwin/default.nix
  lib/compat/default.nix
  modules/system/hm-system-path.nix
  modules/system/options.nix
  profiles/home/fish/default.nix
  profiles/home/navi/default.nix
  profiles/home/paths/default.nix
  profiles/system/darwin/common.nix
  users/eturkeltaub/secrets.nix
Labels: bug

#36 Move tmuxp configuration to `~/.config/tmuxp`
  modules/home/programs/tmuxp/default.nix
Labels: improvement

#37 Add module for `micro`
  flake.nix
  modules/home/programs/micro/default.nix
  profiles/home/micro/default.nix
Labels: feature

#38 Improve `micro` module
  modules/home/programs/micro/default.nix
  profiles/home/micro/default.nix
Labels: improvement

#40 Settings for terminal in VSCode
  profiles/home/vscode/default.nix
Labels: feature

#41 Pin VSCode version for work host
  flake.lock
  flake.nix
  overlays/nixpkgs/overrides.nix
  profiles/system/darwin/common.nix
  users/eturkeltaub/home.nix
  users/eturkeltaub/secrets.nix
Labels: improvement
