Repository ethnt/tilde, pull requests merged in 2023-11, with the labels that each got.

#98 Justfile, README cleanup
  .ecrc
  .github/workflows/ci.dhall
  .github/workflows/ci.yml
  Justfile
  README.md
  flake.lock
  flake.nix
  hosts/eMac/configuration.nix
  modules/darwin/default.nix
  modules/development/dhall.nix
  modules/development/flake-root.nix
  modules/development/shell.nix
  modules/development/treefmt.nix
  modules/home/default.nix
  modules/profiles/default.nix
  modules/profiles/home/fish/default.nix
  modules/profiles/home/navi/default.nix
  modules/profiles/home/starship/default.nix
  modules/profiles/home/tmux/default.nix
  modules/profiles/system/builders/nix-docker.nix
  modules/profiles/system/darwin/common.nix
  modules/profiles/system/darwin/system-defaults.nix
  modules/profiles/system/fonts/common.nix
  modules/profiles/system/gpg-agent/default.nix
  modules/suites/default.nix
  modules/suites/home.nix
  users/default.nix
  users/ethan/home.nix
  users/eturkeltaub/home.nix
  users/eturkeltaub/secrets.nix
Labels: improvement

#99 Make changes to work configuration
  hosts/eMac/configuration.nix
  hosts/st-eturkeltaub2/configuration.nix
  modules/development/dhall.nix
  modules/development/shell.nix
  modules/profiles/system/darwin/brew.nix
  modules/profiles/system/users/eturkeltaub.nix
  users/eturkeltaub/home.nix
Labels: bug

#100 Homebrew cleanup
  .editorconfig
  Justfile
  hosts/eMac/configuration.nix
  lib/compat/darwin/default.nix
  modules/darwin/src/home-manager.nix
  modules/profiles/home/paths/default.nix
  modules/profiles/system/fonts/common.nix
  modules/profiles/system/fonts/pragmatapro.nix
  modules/profiles/system/home-manager/common.nix
  modules/suites/system.nix
Labels: improvement

#101 Build `remote` home configuration on CI, use determinate installer
  .github/workflows/ci.dhall
  .github/workflows/ci.yml
  Justfile
Labels: feature
