Repository ethnt/tilde, pull requests merged in 2024-01, with the labels that each got.

#105 Update inputs
  .gitignore
  flake.lock
  flake.nix
  hosts/eMac/configuration.nix
  modules/profiles/home/git/common.nix
  modules/profiles/home/micro/default.nix
  modules/profiles/home/neovim/default.nix
  modules/profiles/home/nodejs/default.nix
  modules/profiles/home/rtx/default.nix
  modules/profiles/home/tools/common.nix
  modules/profiles/home/tools/extra.nix
  modules/profiles/home/tools/media-management.nix
  modules/profiles/system/builders/builder.nix
  modules/profiles/system/darwin/brew.nix
  modules/profiles/system/darwin/common.nix
  modules/profiles/system/home-manager/common.nix
  modules/suites/home.nix
  users/ethan/home.nix
Labels: feature

#106 Build systems using FlyCI
  .github/workflows/ci.dhall
  .github/workflows/ci.yml
Labels: feature

#107 Fix Nix settings for substituters
  hosts/st-eturkeltaub2/configuration.nix
  modules/profiles/system/cachix/default.nix
  modules/profiles/system/core/nix-config.nix
  modules/profiles/system/darwin/brew.nix
  modules/suites/system.nix
Labels: bug

#108 Use PragmataPro from flake
  flake.lock
  flake.nix
  hosts/default.nix
  hosts/eMac/configuration.nix
  pkgs/default.nix
Labels: feature

#109 Add packages to flake, consume overlay
  flake.nix
  hosts/st-eturkeltaub2/configuration.nix
  modules/profiles/system/fonts/common.nix
  pkgs/default.nix
  pkgs/fonts/pragmatapro.nix
  pkgs/oh-my-tmux.nix
Labels: improvement

#110 Add `nixvim`
  flake.lock
  flake.nix
  modules/home/src/programs/micro/default.nix
  modules/profiles/home/micro/default.nix
  modules/profiles/home/neovim/default.nix
  modules/suites/home.nix
  users/default.nix
Labels: feature

#111 Upgrade to starship 1.17.1
  modules/profiles/home/starship/default.nix
  modules/suites/home.nix
Labels: bug

#112 Add program to remote to upgrade Tilde
  users/remote/home.nix
Labels: feature

#113 Move update-tilde to be a package
  pkgs/default.nix
  pkgs/update-tilde.nix
  users/remote/home.nix
Labels: bug

#114 Add `update-tilde` to overlay
  pkgs/default.nix
Labels: bug

#115 Updates to work secret configuration
  users/eturkeltaub/secrets.nix
Labels: improvement

#116 Move secrets to external flake/repo
  .git-crypt/.gitattributes
  .git-crypt/keys/default/0/4FF658525A04B618E0376A8854CFB5EB45626324.gpg
  .git-crypt/keys/default/0/AFEEB13E64ED9E7ACD5D5C0B15FF752777F78A43.gpg
  .git-crypt/keys/default/0/F9C8B00B4A57FA271F7A896B690FEBBF6380166A.gpg
  .gitattributes
  .github/workflows/ci.dhall
  .github/workflows/ci.yml
  flake.lock
  flake.nix
  modules/core/flake-root.nix
  modules/core/secrets.nix
  modules/development/shell.nix
  modules/profiles/home/git/common.nix
  modules/profiles/system/home-manager/common.nix
  users/default.nix
  users/eturkeltaub/home.nix
  users/eturkeltaub/secrets.nix
Labels: feature

#118 Use main `nix-darwin` fork
  flake.lock
  flake.nix
Labels: improvement

#119 Generate CI config with `nixago`
  .github/workflows/ci.dhall
  .github/workflows/ci.yml
  flake.lock
  flake.nix
  modules/development/ci.nix
  modules/development/dhall.nix
  modules/development/shell.nix
  modules/development/treefmt.nix
Labels: feature

#121 Update `tilde-secrets`
  flake.lock
Labels: improvement
