Repository ethnt/tilde, pull requests merged in 2024-02, with the labels that each got.

#122 Update inputs
  flake.lock
  modules/profiles/home/mise/default.nix
  modules/suites/home.nix
Labels: improvement

#123 Retain current path in new tmux window
  modules/profiles/home/tmux/.tmux.conf.local
Labels: bug

#125 Explicitly set `fish_color_autosuggestion`
  modules/profiles/home/fish/default.nix
Labels: bug

#126 Build `devShells` on CI
  .github/workflows/ci.yml
  modules/development/ci.nix
Labels: feature
