Repository ethnt/tilde, pull requests merged in 2024-03, with the labels that each got.

#128 `fzf` completions in `fish`
  modules/profiles/home/fish/default.nix
  modules/profiles/home/fzf/default.nix
  modules/profiles/home/fzf/fish-integration.nix
Labels: feature

#129 Add `git sync` alias to `hub sync`
  modules/profiles/home/git/common.nix
Labels: feature

#131 Remove `fish` `fzf` integration
  modules/profiles/home/fzf/default.nix
  modules/profiles/home/fzf/fish-integration.nix
Labels: improvement

#132 Upgrade to devenv 1.0.0
  .github/workflows/ci.yml
  flake.lock
  hosts/eMac/configuration.nix
  modules/development/ci.nix
  modules/development/shell.nix
  modules/profiles/home/vscode/default.nix
Labels: improvement

#134 Make VSCode extensions directory mutable again
  modules/profiles/home/vscode/default.nix
Labels: bug

#135 VSCode changes, Homebrew cleanup, remove `asdf`, `lib` annotations
  hosts/st-eturkeltaub2/configuration.nix
  lib/src/utils.nix
  modules/home/src/programs/asdf/default.nix
  modules/profiles/home/asdf/default.nix
  modules/profiles/home/vscode/default.nix
  modules/profiles/system/darwin/brew.nix
  modules/suites/home.nix
  users/eturkeltaub/home.nix
Labels: improvement
