Repository ethnt/tilde, pull requests merged in 2024-09, with the labels that each got.

#145 Update inputs, add `jujutsu`
  Justfile
  flake.lock
  flake.nix
  hosts/default.nix
  lib/compat/darwin/default.nix
  lib/compat/default.nix
  modules/development/treefmt.nix
  modules/profiles/home/jujutsu/default.nix
  modules/profiles/home/nodejs/default.nix
  modules/profiles/home/starship/default.nix
  modules/profiles/home/tools/media-management.nix
  modules/profiles/home/vscode/default.nix
  modules/profiles/system/core/nix-config.nix
  modules/profiles/system/darwin/common.nix
  modules/profiles/system/fonts/common.nix
  modules/profiles/system/home-manager/common.nix
Labels: feature, improvement

#147 Update VSCode extensions, clean up other profiles
  modules/profiles/home/jujutsu/default.nix
  modules/profiles/home/rippkgs/default.nix
  modules/profiles/home/vscode/default.nix
Labels: improvement

#148 Use Attic cache
  .github/actions/setup/action.yml
  .github/workflows/ci.yml
  flake.lock
  flake.nix
  modules/profiles/home/attic/default.nix
  modules/suites/home.nix
Labels: feature

#149 Bump `maxJobs` of `builder`
  flake.nix
  modules/profiles/system/builders/builder.nix
Labels: improvement

#151 Update `tilde-secrets`
  flake.lock
Labels: feature

#152 Update `tilde-secrets` input
  flake.lock
Labels: improvement

#153 Update email, add casks, bump `home.stateVersion`
  hosts/eMac/configuration.nix
  users/ethan/home.nix
  users/eturkeltaub/home.nix
Labels: improvement
